name: CI

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 42.193.100.111
        private-key: ${{ secrets.PRIVATE_KEY }}
        script_stop: true 
        script: ./push.sh

