name: CI

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: 42.193.100.111
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: sh cli
      run: sh ~/cli.sh

