name: CI

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 47.95.116.109
        username: root
        key: ${{ secrets.ACCESS_TOKEN }}
        port: 22
        script: ./push.sh

