name: CI

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: fifsky/ssh-action@master
      with:
        command: sh ~/cli.sh
        host: ${{ secrets.REMOTE_HOST }}
        user: root
        key: ${{ secrets.PRIVATE_KEY }}
